# Generated by Django 4.0.6 on 2022-07-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='titleq',
        ),
    ]
