# Generated by Django 4.0.6 on 2022-07-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_title_about_titleq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='titleq',
            new_name='title',
        ),
    ]
