# Generated by Django 4.0.6 on 2022-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
