# Generated by Django 4.0.6 on 2022-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
