# Generated by Django 4.0.6 on 2022-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_about_description_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
